name: nextar_products
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.4.1+1
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  flutter_modular_test: ^1.0.4
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs