// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa1oGEGzpaJUbKmKD7LJYevOd2l-QIta4',
    appId: '1:613555147280:web:dbebc0e73794b9220f3095',
    messagingSenderId: '613555147280',
    projectId: 'products-test-ac337',
    authDomain: 'products-test-ac337.firebaseapp.com',
    storageBucket: 'products-test-ac337.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKKvcRX9oMEbuNCuUkTfDkKGRUBGJFqQ',
    appId: '1:613555147280:android:6029c36b4807dced0f3095',
    messagingSenderId: '613555147280',
    projectId: 'products-test-ac337',
    storageBucket: 'products-test-ac337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbkQ4_tL3ATFGh_3N1qSs5GZTYQ8iJagQ',
    appId: '1:613555147280:ios:ae34748c01f370060f3095',
    messagingSenderId: '613555147280',
    projectId: 'products-test-ac337',
    storageBucket: 'products-test-ac337.appspot.com',
    iosClientId: '613555147280-4f7i317uc8vsikphe0i7o8v5usmhpvon.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextarProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbkQ4_tL3ATFGh_3N1qSs5GZTYQ8iJagQ',
    appId: '1:613555147280:ios:ae34748c01f370060f3095',
    messagingSenderId: '613555147280',
    projectId: 'products-test-ac337',
    storageBucket: 'products-test-ac337.appspot.com',
    iosClientId: '613555147280-4f7i317uc8vsikphe0i7o8v5usmhpvon.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextarProducts',
  );
}
